server:
    port: 8090

spring:
    datasource:
        platform: h2
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource
        url: jdbc:h2:mem:jhipster;DB_CLOSE_DELAY=-1
        databaseName: 
        serverName: 
        username: 
        password: