server:
    port: 8080

spring:    
    datasource:
        platform: mysql
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://localhost:3306/test
        databaseName: test
        serverName: localhost
        username: root
        password: 1234
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true